#!/bin/bash
#
# fedora-review git pre-commit hook: run pep8 and pylint


ALL_FILES=$( git diff --cached --name-status |
              grep -v ^D | awk '$1 $2 { print $2}' | grep -e '.py$' )

if [ -z "$ALL_FILES" ]; then
    exit 0
fi

pep8 --config pep8.conf  $ALL_FILES || {
    echo "pep8 failed. Fix your code!"
    echo "*If* you know what you are doing, use 'git commit --no-verify'"
    exit 1
}

SRC_FILES=''
TEST_FILES=''
for file in $( echo $ALL_FILES ); do
    if [[ $file == test/* ]]; then
        TEST_FILES="$TEST_FILES ${file##test/}"
    else
        SRC_FILES="$SRC_FILES $file"
    fi
done

if [ "$TEST_FILES" ]; then
    cd test
    export PYTHONPATH=../src
    pylint --rcfile=../pylint.conf -f text $TEST_FILES > pylint.log || {
        echo "Pylint failed for test files, log in test/pylint.log"
        echo "Fix test code or use --no-verify."
        exit 3
    }
    cd $OLDPWD
fi
if [ "$SRC_FILES" ]; then
    export PYTHONPATH=src
    pylint --rcfile=pylint.conf -f text $SRC_FILES > pylint.log || {
        echo "Pylint failed, log in pylint.log."
        echo "Fix code or use --no-verify."
        exit 3
    }
fi
