.TH "fedora-review" 1
.SH NAME
fedora-review \- Automatically review RPM packages for Fedora.

.SH SYNOPSIS
.B fedora-review
-b <bug number>
.br
.B fedora-review
-n <package name>

.SH DESCRIPTION

This tool makes reviews of rpm packages for Fedora easier. It tries to automate most of the process.
Through a json API the checks can be extended in any programming language and for any programming language.
We have at the moment checks for C/C++, R, Java and Perl packages.

.SH USAGE
This program runs a number of checks  for packages in Fedora.
.HP
fedora-review -b <bug number>

It will download the SPEC & SRPM files from the Bugzilla report and
build them in mock and run a number of test and generate a report
there will be opened in editor along with the spec file, so the things
not automated can be reviewed manually.

.HP
fedora-review -n <package name>

This alternative usage expects <package name>.spec and source rpm in current
directory.

.PP
You will need to have mock installed and be member of the mock group
for the build to work. Run as root:
.HP
 usermod -a -G mock [your user name] && newgrp mock


.SH OPTIONS
.B -b / --bug
    Identifier of the ticket on the bugzilla where is the package to review.
.sp
.B -n / --name
    Runs the checks against the named spec and source rpm located in the current working directory.
.sp
.B -w / --workdir
    Specify in which working directory to work.
.sp
.B --other-bz
    URL for another bugzilla.
.sp
.B --assign
    Assign the bugzilla ticket to yourself.
.sp
.B --cache
    Do not redownload the files from bugzilla, use the local one.
.sp
.B --nobuild
    Do not rebuild the source rpm, use the currently built one.
.sp
.B -u / --user
    Bugzilla user name.
.sp
.B  -p / --password
   Bugzilla password.
.sp
.B  -v / --verbose
   Provides a more detailed output of what's going on.
.sp
.B --no-report
   Do not generate the review report.
.sp
.B --mock-config
   Specify which mock config to use

.SH FILES
.I $HOME/.conf/fedora-review/settings
.RS
User configuration files for fedora-review
.RE

.I /usr/share/fedora-review/plugins
.RS
System-wide external plugins directory
.RE

.I $HOME/.conf/fedora-review/plugins/
.RS
User supplied external plugins directory
.RE

.SH ENVIRONMENT
.TP
.B  REVIEW_EXT_DIRS
    If REVIEW_EXT_DIRS is set, it specifies additional directories that will be searched for external plugins

.SH AUTHORS
  Original author: Tim Lauridsen <tim.lauridsen@gmail.com>

  Developers:
      Stanislav Ochotnicky <sochotnicky@redhat.com>
      Pierre-Yves Chibon <pingou@pingoured.fr>

  For a list of all contributors see AUTHORS file

.sp
.sp
No known bugs at this time
