.TH "fedora-review" 1
.SH NAME
fedora-review \- Automatically review RPM packages for Fedora.

.SH SYNOPSIS
.B fedora-review
[options] [bugzilla options] -b <bug>
.br
.B fedora-review
[options] [--prebuilt] -n <package name>
.br
.B fedora-review
[options] -u <url>

.SH DESCRIPTION

This tool makes reviews of rpm packages for Fedora easier. It tries to automate most of the process.
Through a json API the checks can be extended in any programming language and for any programming language.
We have at the moment checks for C/C++, R, Java and Perl packages.

.SH USAGE
This program runs a number of checks for packages in Fedora.
.IP "" 4
$ fedora-review -b <bug number>
.br
$ fedora-review -u <url>
.PP
Will download the SPEC & SRPM files from the Bugzilla report,
build them in mock, run a number of tests and generate a report.

Not all bugzillas support the -b option. The -u option only allows for
downloads and is not as reliable as -b, but works in many cases.
See  --url usage notes below.
.IP "" 4
$ fedora-review -n <package name>
.PP
This alternative usage expects <package name>.spec and source rpm in current
directory. By adding the -p switch, fedora-review uses already built rpms
in current directory instead of building using mock.
.PP
You will need to have mock installed and be member of the mock group
for the build to work. Run as root:
.IP "" 4
# usermod -a -G mock [your user name] && newgrp mock
.PP
To assign bugs in bugzilla automatically you will first have to login
into bugzilla (--login). This will create a bugzilla cookie so you
don't have to login every time.
.SH MODE OPTIONS - one is required
.TP 4
.B -b, --bug <bug nr>
Run against Fedora bugzilla at bugzilla.redhat.com, using the bugzilla
bug number
.TP 4
.B -n, --name <name>
Runs the checks against the named spec and source rpm located in the
current working directory. The files are expected to hane the names
<name>.spec and <name>*.src.rpm.
.TP 4
.B -u url, --url <url>
Fetch data from given url, typically another bugzilla instance without
xmlrpc support such as rpmfusion. For more modern sites with xmlrpc
support, first try --bug <bug nr> --other-bz <url>.
The option tries to retrieve the URL:s by scanning the page.
As for --bug links has to end with '.src.rpm' and '.spec' to
be found.
.TP 4
.B  -d, --display-checks
List all available checks, usable as arguments to --exclude and
--single
.TP 4
.B  -V, --version
Show version info
.SH GENERAL OPTIONS
.TP 4
.B -c, --cache
Do not redownload the files from bugzilla, use the local one.
.TP 4
.B -m, --mock-config <configuration>
Specify which mock config to use, one of the files in /etc/mock,
with the .cfg suffix stripped. Defaults to the root defined in
/etc/mock/default.cfg
.TP 4
.B -o, --mock-options "options..."
Mock options the build. Defaults to --no-cleanup-after, you might
want this along with other options
you provide.
.TP 4
.B --no-report
Do not generate the review report.
.TP 4
.B --no-build
Do not rebuild the source rpm, use the one currently built in mock.
.TP 4
.B -p, --prebuilt
When using -n <name>, use prebuilt rpms in current directory instead
of building new ones in mock
.TP 4
.B -r, --rpm-spec
Instead of using a spec file URL, use the spec file bundled in the srpm file.
.TP 4
.B -s test, --single test
Run a single test, as listed by --display-checks
.TP 4
.B  -v, --verbose
Provides a more detailed output of what's going on.
.TP 4
.B -x  "test1, test2, ...", --exclude "test1, test2, ..."
Comma-separated list of test(s) to exclude, as listed by --display-checks
.TP 4
.B -k, --checksum {md5,sha1,sha224,sha256,sha384,sha512}
algorithm used for checksum (currently supported: md5, sha1, sha224, sha256, sha384, sha512)
.SH BUGZILLA OPTIONS
.TP 4
.B -a, --assign
Assign the Fedora bugzilla ticket to yourself. Only known to work with bugzilla.redhat.com
.TP 4
.B -l, --login "Fedora FAS user id"
Login into Fedora Bugzilla before starting.
.TP 4
.B -o url,--other-bz url
URL for another bugzilla.
.TP 4
.B -i id, --user userid
The bugzilla user id.
.SH THE REVIEW DIRECTORY
The report template create by fedora-review lives in a review directory. 
Besides the report, here is:
.TP 4
srpm directory
Holds whats downloaded, normally a src.rpm and a 
spec file. When using --rpm-spec, here is no .spec file.
.TP 4
srpm-unpacked directory
Holds the unpacked content of the src.rpm
file.
.TP 4
upstream directory 
contains sources downloaded from the Source: url in the spec file.
.TP 4
upstream-unpacked directory 
Occasionally contains the unpacked sources, but is normally empty.
.TP 4 
BUILD link 
Points to the mock directory containing the sources used in 
the build. These sources have been created and modifified by the %prep
stuff in the spec file. The link is only valid direct after the run, 
it's overwritten next time mock executes.
.TP 4
result link 
Points to the mock result dir, containing logs and rpms.
This is also overwritten as soon as mock is run again e. g., by 
fedora-review.
.SH LOCAL SOURCES (GIT-BASED OR SIMILAR)
Normally, the Source0 (or others SourceX) in the specfile contains an URL
to the upstream source. fedora-review uses this url to download the 
upstream source and then compare md5sum with source in rpm.

However, in some cases the Source0: is just a filename e. g., when sources
are generated from git, svn or similar tools. In these cases, fedora-review
will look for a file matching the Source0 in current directory. If it exists,
it's used as upstream source. This way, a reviewer can generate the source
according the comments in the spec before running fedora-review and then
have it checked.

.SH URL limitations
fedora-review handles two types of URL: the spec and srpm url found in 
e. g. the bugzilla page, and the source url(s) found in the spec file.

For the srpm and spec file url:
.IP \(bu 3 
The parameters (i. e., the ? and everything beyond) is removed. 
.IP \(bu 3
The rest must end with /*.spec or /*.src.rpm

.P
For the source url, possible parameters are 
.B not
removed. It must end with /filename, typically something like
/package-2.0.1.tar.gz


.SH EXAMPLES
Make a report template for Fedora bug 817271:
.IP "" 4
$ fedora-review -b 817271
.PP
fetches spec and srpm file from bugzilla.redhat.com and makes a report.
To instead handle a bug at rpmfusion use something like
.IP "" 4
$ fedora-review --url \\
.br
https://bugzilla.rpmfusion.org/show_bug.cgi?id=2150 \\
.br
--mock-config fedora-16-i386-rpmfusion_free
.PP
Occasionally, fedora-review isn't able to pick up the links e. g.,
when the links does not end in .spec and/or .src.rpm. In these case
you need to download files manually. Using --rpm-spec only the srpm
is needed:
.nf
.IP "" 4
$ wget http://somewhere.com/bad-srpmlink -O my-package-1.2-1.fc16.src.rpm
$ fedora-review --rpm-spec -n my-package
.fi
.PP
This works if (and only if) the local files has name with correct prefix
as given to -n (my-package in this example). The filenames must also end
with \.spec and \.src.rpm
.PP
Finally, you can assign the bug from the commandline:
.nf
.IP "" 4
$ fedora-review -b 811221 --assign --user my-bugzilla-id --login
password:

.SH FILES
.I $HOME/.cache/fedora-review.log
.RS
Debug logging from last session.
.RE
.I $HOME/.bugzillacookies
.RS
Persistent credentials setup when using --login.
.RE
.I /usr/share/fedora-review/plugins
.RS
System-wide external plugins directory
.RE
.I $HOME/.config/fedora-review/plugins/
.RS
User supplied external plugins directory
.RE

.SH ENVIRONMENT
.TP
.B  REVIEW_EXT_DIRS
If REVIEW_EXT_DIRS is set, it specifies additional directories that will be searched for external plugins
.TP
.B REVIEW_LOGLEVEL
loglevel used when not using -v/--verbose. A logging.* value like 'DEBUG', 'Info', or 'warning'. Setting
REVIEW_LOGLEVEL to 'debug' is the same as providing the -v/--verbose option.

.SH AUTHORS
Original author: Tim Lauridsen <tim.lauridsen@gmail.com>

Developers:
    Stanislav Ochotnicky <sochotnicky@redhat.com>
    Pierre-Yves Chibon <pingou@pingoured.fr>

For a list of all contributors see AUTHORS file

.SH SEE ALSO
https://fedorahosted.org/FedoraReview/  - source, issue tracker, etc.
