#!/usr/bin/python
#    -*- coding: utf-8 -*-
#
# See: https://bugzilla.redhat.com/show_bug.cgi?id=675140#c1
# From: http://people.redhat.com/mikeb/scripts/download-scratch.py


#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import os.path
import sys


# Load from site lib
from distutils.sysconfig import get_python_lib
sitedir = os.path.join(get_python_lib(), 'FedoraReview')
if os.path.exists(sitedir):
    sys.path.insert(0, sitedir)

# Load from development lib
here = os.path.dirname(os.path.realpath(__file__))
srcdir = os.path.join(here, 'src', 'FedoraReview')
if os.path.exists(srcdir):
    sys.path.insert(0, srcdir)

import download_scratch


try:
    download_scratch.main()
except Exception as err:
    print err

