#!/bin/bash
# reads version from setup.py, create a source tarball and optionally
# upload to fedorahosted
#
# Options: -b  Batch mode, don't ask for fedorahosted upload

newdir=`mktemp --tmpdir -d fedora-review-release-XXXXX`

git clone $( dirname $( readlink -fn $0 )) $newdir

cd ${newdir}


status=$( git status --short )
[ -n "$status" ] && echo 'Warning: there are uncommitted changes' >&2

badlinks=$( find . -type l ! -execdir test -e '{}' \; -print | nl )
[ -n "$badlinks" ] && echo "Warning: unresolved  symlinks: $badlinks" >&2

./update-version

source src/FedoraReview/version
dfile="dist/fedora-review-$__version__.tar.gz"

[ -f ${dfile} ] && echo Removing: $dfile
rm -f $dfile

env PYTHONPATH=src python setup.py --quiet clean
env PYTHONPATH=src python setup.py --quiet build sdist
if [ ! -e "$dfile" ];  then
    echo "Error: could not create $dfile"
    exit 1
fi
echo "Created: $dfile"

echo "Running tests on tarball before finalizing release"
tar -xf $dfile && pushd fedora-review-$__version__
REVIEW_LOGLEVEL=error src/test/run-tests.py
if [ $? -ne 0 ]; then
    echo "Some tests failed. Review test logs and fix all problems"
    echo "before doing a release. Aborting"
    exit 1
fi
popd
[ "$1" = '-b' ] && exit 0

read -i 'n' -e -p "Do you want to upload file $dfile to fedorahosted? (y/n): "
if [ "$REPLY" = "y" ];then
    scp "${dfile}" fedorahosted.org:FedoraReview
    git tag $__version__
    git push --tags
    echo "Things to do now:"
    echo "      1. Merge to 'master' and 'devel'"
    echo "      2. Update trac releases and tickets"
    echo "      3. Build rpms for Fedoras/EPEL"
    echo "      4. Create updates in bodhi"
    echo "      5. Announce!"
    echo "      6. (nice to have) Update trac queries for new milestone"
fi
