#!/bin/bash
#
# Run f-r with or in a directory created by dist-check-setup and with
# everything downloaded e. g. using download-dir.

[[ -n "$1" && -d "$1" ]] && cd "$1"

readonly DISTTAG='fc20'
export XDG_CACHE_HOME=$PWD
export REVIEW_LOGLEVEL=${REVIEW_LOGLEVEL:-info}
[ -x ../../bin/mock ] && export PATH="../../bin:$PATH"

arch=$(uname -i)
my_skipped="CheckNoNameConflict,CheckOwnDirs"

echo PATH: $PATH

try-fedora-review -rpn ${PWD##*/} -m fedora-rawhide-$arch \
    -x ${REVIEW_SKIP:-$my_skipped} -D DISTTAG=fc20 -D BATCH

