#!/bin/bash
#
# Touch the jenkins GIT plugin, possibly starting a build.
#
# See: https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin
# See: http://jenkins.turbogears.org/

api_base='http://jenkins.turbogears.org'
branches='&branches=devel'
repo_url='http://git.fedorahosted.org/git/FedoraReview.git'

reply=$( wget -qO - \
         "$api_base/git/notifyCommit?url=$repo_url$branches" )
rc=$?
echo $reply
exit $rc
