#!/bin/bash
#
# Run tests, the jenkins way.
#
# Requires: python-virtualenv, python-pip


function install_virtenv()
{
    rm -fr fedorareviewenv
    virtualenv --system-site-packages fedorareviewenv
    source fedorareviewenv/bin/activate
    pip  install -q nose --upgrade  ## Needed within the venv
    pip  install -q nosexcover
    hash -r  ## Reload where the nosetests app is (within the venv)
}

args="$@"

cd $(dirname $(readlink -fn $0))
cd ..

if [[ -n "$PIP_INSTALL" || ! -d fedorareviewenv ]]; then
        install_virtenv
fi
source fedorareviewenv/bin/activate
hash -r

nose_vers=$(nosetests --version) || :
if [[ "$nose_vers" != *1.2* ]]; then
    install_virtenv
    source fedorareviewenv/bin/activate
    hash -r
fi

PYTHONPATH=src ./update-version || :
cd test
export REVIEW_LOGLEVEL=${REVIEW_LOGLEVEL:-warning}
mock -q --shell "echo default root OK >/dev/null" || mock --quiet --init
mock -qr fedora-17-i386 --shell "echo 17-i38 OK >/dev/null" ||\
     mock --quiet -r fedora-17-i386 --init
mock -qr fedora-16-i386 --shell "echo 16-i38 OK >/dev/null" || \
    mock --quiet -r fedora-16-i386 --init
mock -qr fedora-17-i386 --uniqueext=hugo \
    --shell "echo 17-i386  uniqueext=hugo OK >/dev/null" || \
    mock --quiet -r fedora-17-i386 --uniqueext=hugo --init

nosetests -svx -e init_test -e init_opt_test --cover-erase \
    --cover-package=plugins,FedoraReview \
    ${REVIEW_NOSEOPTS:- --with-xunit --with-xcoverage} \
    "${args[@]}"


# vim: set expandtab ts=4 sw=4:
