#!/usr/bin/python -tt
#    -*- coding: utf-8 -*-

#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


"""
This program aims to provide a simple way to create review-request on
the Red Hat's bugzilla for Fedora products.

The idea is:
- from a spec and srpm
  - start a koji scratch build
  - if build worked
    - upload to fedorapeople.org
    - create the bugzilla ticket
    - Add the koji build in the bugzilla as a link
  - otherwise:
    - warn user
"""

import os.path
import sys


# Load from site lib
from distutils.sysconfig import get_python_lib
sitedir = os.path.join(get_python_lib(), 'FedoraReview')
if os.path.exists(sitedir):
    sys.path.insert(0, sitedir)

# Load from development lib
here = os.path.dirname(os.path.realpath(__file__))
srcdir = os.path.join(here, 'FedoraReview')
if os.path.exists(srcdir):
    sys.path.insert(0, srcdir)

import create_review

try:
    create_review.ReviewRequest().main()
except Exception as err:
    print err
